### ISSUE TITLE
QuotaError not reported correctly

### ISSUE THREAD

**Issue by ThomasMatern** [3ptscience/steno3dpy#134]
Uploading a second project to an account on a community plan correctly raises a `ProjectQuotaExceeded`.
However, uploading two projects simultaneously leads to one successfully uploaded project while the other one returns an `UploadError` with a `QuotaException`

Also noteworthy is that the error messages are slightly different:
`ProjectQuotaExceeded`:
Uploading this private project will put you over your quota of 1 private project(s). For more projects and space, consider upgrading your account: https://steno3d.com/settings/plan

`UploadError`:
QuotaException: Creating a new private ProjectSteno3D would put <me> over quota. For more projects and space, consider upgrading to a Professional account (https://steno3d.com/settings/plan).

**Comment by fwkoch** [comment]
Hey @ThomasMatern - This makes sense. When uploading projects simultaneously, the initial quota check (which raises `ProjectQuotaExceeded` will pass for both). However, only one will successfully upload; whichever upload completes second will fail with just an `UploadError` from the database. The error messages for these come from different places.

This should be fixed in this PR: https://github.com/3ptscience/steno3dpy/pull/135 - if a project post fails, quota check is performed again, resulting in `ProjectQuotaExceeded`.

**Comment by ThomasMatern** [comment]
Thanks Franklin, the explanation makes sense and the fix does work.
