### ISSUE TITLE
Windows Permission Error

### ISSUE THREAD

**Issue by rowanc1** [3ptscience/steno3dpy#47]
I have talked to two people now that have problem with permissions with a temporary file. 

Running it locally but they have got the following error when they run `my_surf.upload(sync=True)`: 

```
IOError: [Errno 13] Permission denied: u'c:\\users\\username\\appdata\\local\\temp\\tmp6inigr.dat'
```

This error happens on Windows 10.

Any thoughts on this @fwkoch?

**Comment by fwkoch** [comment]
When uploading arrays (data, vertices, triangles, etc.), a `NamedTemporaryFile` is created, the array is written to the file using `numpy.ndarray.tofile`, then the file is uploaded. This bug occurred because we were passing `temp_file.name` into `tofile`, requiring `tofile` to re-open the temporary file. This behaviour is fine on Unix, but on Windows temporary files cannot be re-opened (documented here: https://docs.python.org/2/library/tempfile.html). This is fixed by simply passing `temp_file.file` into `tofile` instead.

**Comment by fwkoch** [comment]
Fix here: https://github.com/3ptscience/steno3dpy/pull/48/commits/f533923b7d2e22532fc1b3cab3a700b9de33e575

To be deployed today with v0.2.2.

**Comment by fwkoch** [comment]
v0.2.2 deployed to PyPI:

`>> pip install --upgrade steno3d`

If the problem persists, please reopen this issue.
