### ISSUE TITLE
How do construct a vertical planar surface such as a crossection without having volume data?

### ISSUE THREAD

**Issue by hal98x** [3ptscience/steno3dpy#75]
I have grid of ERT data so x=length along line and y = depth. The syntax in the api suggests that Mesh 2D is more for a primarily horizontal than vertical surface. 

How do I display this 2D ERT section. I think I could do it with a TIN but my hang up is converting conductivity values of square grid to a triangular grid. Any insight or help would be much appreciated.

**Comment by rowanc1** [comment]
Although this is supported in steno3d mesh2dgrid, the python client is not reflecting that.

Looking through the code on line 216 of surface.py:
```python
        if ('h1' in dirty or 'h2' in dirty or 'x0' in dirty) or force:
            datadict['OUV'] = dumps(dict(
                O=self.x0.tolist(),
                U=[self.h1.sum().astype(float), 0, 0],
                V=[0, self.h2.sum().astype(float), 0],
            ))
```

The `OUV` parameter will specify the orientation of the grid in space (as a parallelogram). Right now it is forced to be going horizontal. We will fix this up and get it tested and deployed in the next 4 days. @fwkoch is also working on a higher level API that should have this much easier to plot cross sections (similar to matlab style plotting, if you are familiar with that).

Thanks for bringing this to our attention.

**Comment by fwkoch** [comment]
@hal98x -

Thanks again for bringing this up. I have implemented this functionality in `Mesh2DGrid`, and it is currently in beta (v0.2.9b0). To access this version `pip install --upgrade --pre steno3d`. If you run into any critical bugs, you can revert to the more stable version by uninstalling then reinstalling without the `--pre`.

Since this is just in pre-release, there isn't documentation online yet. However, the implementation is similar to `O`, `U`, `V` of [Texture2DImage](https://python.steno3d.com/en/latest/content/api/resources/texture.html). `O` is the origin, renamed from `x0` (you should just get a warning if you keep using `x0`), `U` is a vector corresponding to the orientation of the `h1` axis and `V` is a vector corresponding to the `h2` axis. (Note: U and V are only used for orientation. Axis length still comes from the h-arrays). For `U` and `V` you may use "X", "Y", "Z" or length-3 vectors. Previous default behaviour is maintained with U and V defaulting to "X" and "Y" respectively.

For example, if you have an ERT section oriented at 45 degrees, you can do something like:

``` python
ert_surf = steno3d.Surface(
    project=...,
    mesh=steno3d.Mesh2DGrid(
        h1=[...],
        h2=[...],
        O=[0, 0, -100],
        U=[1, 1, 0],
        V='Z',
    ),
    data=...
)
```

I'll keep this issue open until this feature gets tested further and merged into the stable version (probably by the end of the week). Please try it out and let us know if you run into any additional problems.

**Comment by fwkoch** [comment]
This is deployed to the stable version on pip as of this afternoon. Suface doc page is here: https://python.steno3d.com/en/latest/content/api/resources/surface.html Release tag is here: https://github.com/3ptscience/steno3dpy/releases/tag/v0.2.9
